Solution
mate-academy/py-create-file-from-terminal pull request #1036
Opened 2024-10-22 13:22 UTC by YaroslavK87

2024-10-22 13:57 UTC, MrEgorLite approved these changes
👍

2024-10-22 13:58 UTC, mateacademy-ai-mentor approved these changes
Great job on handling the logic for the `-f` condition! 🎉 Just make sure to adjust the line numbering as suggested. Keep up the good work and happy coding!

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-10-22 13:58 UTC, mateacademy-ai-mentor commented on app/create_file.py
> +        line_number = 1
The line number should start from 1, but it is incremented before writing the first line. Initialize `line_number` to 0 instead, so the first line written will be numbered 1.

2024-10-22 13:58 UTC, mateacademy-ai-mentor commented on app/create_file.py
> +    if flag == "-d" and "-f" not in sys.argv:
The condition `'-f' not in sys.argv` is correct, but ensure that the logic handles cases where `-f` is present correctly. The current logic seems to handle this, but double-check for any edge cases.

2024-10-22 13:58 UTC, mateacademy-ai-mentor commented on app/create_file.py
> +    elif flag == "-d" and "-f" in sys.argv:
The condition `'-f' in sys.argv` is correct, but ensure that the logic handles cases where `-f` is present correctly. The current logic seems to handle this, but double-check for any edge cases.

2024-10-23 08:07 UTC, AnyoneClown requested changes

2024-10-23 08:07 UTC, AnyoneClown commented on app/create_file.py
> +        line_number = 1
+, fix this

2024-10-23 08:07 UTC, AnyoneClown commented on app/create_file.py
> +        create_file(file_path)
Create `if __name__ == "__main__"` block to use your entrypoint function

2024-11-21 14:35 UTC, closed without merging