Solution
mate-academy/py-create-file-from-terminal pull request #148
Opened 2022-10-10 12:14 UTC by TetyanaPavlyuk

2022-10-11 09:20 UTC, IvanRamyk requested changes

2022-10-11 09:20 UTC, IvanRamyk commented on app/create_file.py
> +        if "-f" in file_data:
otherwise, path remains an empty value and line 18 will cause an error

2022-10-11 09:20 UTC, IvanRamyk commented on app/create_file.py
> +for line in sys.stdin:
it's easier to use `sys.argv`

2022-10-11 09:20 UTC, IvanRamyk commented on app/create_file.py
> +for line in sys.stdin:
But you can choose your own approach

2022-10-12 13:02 UTC, IvanRamyk commented on app/create_file.py
> +            break
then you don't need these breaks

2022-10-12 13:04 UTC, IvanRamyk commented on app/create_file.py
> +for line in sys.stdin:
please write a function with all logic
also, think about splitting the whole functionality into several functions that perform different steps of the task

2022-10-17 08:13 UTC, DmytroSvirsa requested changes

2022-10-17 08:13 UTC, DmytroSvirsa commented on app/create_file.py
> +            raise ValueError
provide exeption message

2022-10-18 07:43 UTC, DmytroSvirsa approved these changes

2024-03-07 07:40 UTC, closed without merging