Create file
mate-academy/py-create-file-from-terminal pull request #174
Opened 2022-11-09 19:40 UTC by bythewaters

2022-11-10 09:16 UTC, DmytroSvirsa requested changes
too many checks of "-f" tag create aditional function, and make it with only one "-f" tag check

2022-11-11 09:03 UTC, DmytroSvirsa requested changes

2022-11-11 09:03 UTC, DmytroSvirsa commented on app/create_file.py
> +        line_char += 1
you can put the input statement inside the with statement and wright it directly to the file it will work much better with memory

2022-11-11 14:39 UTC, bythewaters commented on app/create_file.py
> +        line_char += 1
Oh, it's really work faster, but why? This is due to the hash function? 
just moving to the next topic)

2022-11-11 15:30 UTC, DmytroSvirsa requested changes

2022-11-11 15:30 UTC, DmytroSvirsa commented on app/create_file.py
>              file.write(data_file + "\n")
you can make it even faster if you will write each input separately in file inside the while loop

2022-11-14 09:09 UTC, Abnormaltype requested changes

2022-11-15 08:05 UTC, Abnormaltype approved these changes
Well done!

2024-06-10 16:56 UTC, closed without merging