Solution
mate-academy/py-create-file-from-terminal pull request #24
Opened 2022-06-07 13:52 UTC by darten360

2022-06-08 12:46 UTC, rotsen18 requested changes
Main problem is that your app woun't work from terminal. There isn't func call inside.

2022-06-10 15:11 UTC, rotsen18 approved these changes

2022-06-10 15:11 UTC, rotsen18 commented on app/create_file.py
> +        os.makedirs(
Here you do not check if such a path already exists, although in lines 9-10 there is such a check. If you add the same check here, you will not follow the DRY principle. It may be best to divide the functions more carefully into folder and file creation, but that's up to you. And try to not use f,i,k,v for variables name.

2022-06-15 10:36 UTC, TPolina commented on app/create_file.py
> +            count = 1
where do you need this variable?

2022-06-15 10:39 UTC, TPolina commented on app/create_file.py
> +    def create_full_path(path, name):
take `create_full_path` function outside `create_file` function.

2022-06-15 10:42 UTC, TPolina commented on app/create_file.py
> +        os.makedirs(
I agree, better write separate function `create_dirs` and use it

2022-06-16 16:12 UTC, closed without merging