Solution
mate-academy/py-create-file-from-terminal pull request #251
Opened 2023-02-22 07:34 UTC by NEkropo1

2023-02-22 17:41 UTC, DavidGlusch approved these changes

2023-02-23 17:32 UTC, YuriiKindrat requested changes

2023-02-23 17:32 UTC, YuriiKindrat commented on app/create_file.py
> +        os.makedirs(dir_path, exist_ok=True)
u can write separate func for this

2023-02-23 17:32 UTC, YuriiKindrat commented on app/create_file.py
> +            break
add blank line if command == "stop". In the examples of the task when inserting new text, first comes the empty line, and then the new values

2023-02-23 17:32 UTC, YuriiKindrat commented on app/create_file.py
> +            f.write(f"{line}\n")
why do u need to use with open for 3 times? optimize that

2023-02-23 17:45 UTC, NEkropo1 commented on app/create_file.py
> +            break
Where? I see no new lines.
![image](https://user-images.githubusercontent.com/107141441/220987553-17c14dd8-a2d2-42ee-af6d-f524c10834bd.png)
![image](https://user-images.githubusercontent.com/107141441/220987613-f01c0a6d-b64e-4bde-9974-2934cda2253c.png)

2023-02-23 17:46 UTC, NEkropo1 commented on app/create_file.py
> +            break
![image](https://user-images.githubusercontent.com/107141441/220987842-c9a9e071-8d3e-40df-a7b1-b42f1d2759a1.png)

2023-02-23 18:21 UTC, NEkropo1 commented on app/create_file.py
> +            break
If you meant that I should provide lines with /n, like in this screen:
![image](https://user-images.githubusercontent.com/107141441/220996064-20825301-245e-49f1-bf2e-e647a1bc6fd6.png)
My code provides it after taking all input, to every item added:
    `f.write(f"{line}\n")`

2023-02-24 17:24 UTC, YuriiKindrat approved these changes

2025-08-11 09:48 UTC, closed without merging