Solution
mate-academy/py-create-file-from-terminal pull request #276
Opened 2023-02-25 14:02 UTC by oksana-feshchenko

2023-02-27 20:09 UTC, myroslavatrschk approved these changes

2023-02-28 12:30 UTC, YuriiKindrat requested changes

2023-02-28 12:30 UTC, YuriiKindrat commented on app/create_file.py
> +                break
add blank line if command == "stop". In the examples of the task when inserting new text, first comes the empty line, and then the new values

2023-02-28 12:30 UTC, YuriiKindrat commented on app/create_file.py
> +            os.makedirs(path)
u can use makedirs argument "exist_ok" here

2023-02-28 12:46 UTC, closed without merging

2023-03-02 13:36 UTC, YuriiKindrat approved these changes