Solution
mate-academy/py-create-file-from-terminal pull request #403
Opened 2023-06-19 19:00 UTC by erikagayan

2023-06-20 12:42 UTC, Altahoma requested changes

2023-06-20 12:42 UTC, Altahoma commented on app/create_file.py
> +def create_file(directory: str, filename: str) -> None:
For what is `directory: str` here if you don't use it?
This function does not create a file by path.
Command: `python create_file.py -d dir1 dir2 -f file.txt` creates the following folders: `dir1 -> dir2 -> -f -> file.txt`, even "file.txt" is a folder and creates the file `file.txt` in the local folder.

2023-06-20 12:42 UTC, Altahoma commented on app/create_file.py
> +            content = file.readlines()
Why do you copy the content if you can just write new lines to the end of the file using mode `a`?

2023-06-20 12:42 UTC, Altahoma commented on app/create_file.py
> +    print("File created successfully.")
There is no need for `print()`.

2023-06-20 12:42 UTC, Altahoma commented on app/create_file.py
> +def file() -> None:
Better to use descriptive names that describe the function's purpose. For exmaple: `run_app`, `parse_commsnds`, `check_flags`.

2023-06-20 12:42 UTC, Altahoma commented on app/create_file.py
> +        create_file(directory, filename)
This will raise an error if we only want to create a file. It also does not provide the ability to write to an existing file.
Check: `python create_file.py -f file.txt`

2023-06-21 12:18 UTC, Altahoma requested changes

2023-06-21 12:18 UTC, Altahoma commented on app/create_file.py
> +        time = datetime.datetime
No need to write `datetime.datetime` if you import a single module.

2023-06-21 19:12 UTC, Altahoma approved these changes
Greate job!

2023-06-22 14:02 UTC, YuriiKindrat approved these changes

2023-08-10 15:49 UTC, closed without merging